### ISSUE TITLE
Did not start

### ISSUE THREAD

**Issue by dcromster** [Shawn-Shan/fawkes#107]
Hello!

When I start fawkes I got this errors:

Traceback (most recent call last):
  File "/usr/local/bin/fawkes", line 33, in <module>
    sys.exit(load_entry_point('fawkes==0.3.1', 'console_scripts', 'fawkes')())
  File "/usr/local/lib/python3.6/dist-packages/fawkes/protection.py", line 210, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
  File "/usr/local/lib/python3.6/dist-packages/fawkes/protection.py", line 53, in __init__
    self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
  File "/usr/local/lib/python3.6/dist-packages/fawkes/protection.py", line 53, in <listcomp>
    self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
  File "/usr/local/lib/python3.6/dist-packages/fawkes/utils.py", line 406, in load_extractor
    model = keras.models.load_model(model_file)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 273, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

OS: Ubuntu 18.04
Python: Python 3.6.8

**Comment by MarkSCQ** [comment]
https://github.com/Shawn-Shan/fawkes/issues/75
I think this will help

**Comment by xirkus** [comment]
No debugging or dependency troubleshooting required: https://dev.scrb.ai
