### ISSUE TITLE
Errors during run of binary software -  ImportError: DLL load failed with error code -1073741795

### ISSUE THREAD

**Issue by panderlad** [Shawn-Shan/fawkes#116]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>CD C:\Users\principal\protection

C:\Users\principal\protection>protection-v0.3.exe -d C:\Users\pr
incipal\foto\cloaked
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_impor
t_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_impor
t_helper
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protection.py", line 13, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\__init__.py", line 28, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_impor
t_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_impor
t_helper
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[7036] Failed to execute script protection

C:\Users\principal\protection>

**Comment by xirkus** [comment]
You can try https://dev.scrb.ai. Doesn't require installation ;-)

**Comment by panderlad** [comment]
Same problem,.look: https://dev.scrb.ai/otonaroid-scrubbed.jpeg

-------- Original Message --------

**Comment by xirkus** [comment]
Yup. That's why I chimed in ;-)

**Comment by emilywenger** [comment]
@xirkus See comment on Issue #120
