### ISSUE TITLE
keras.models.load_model  Unknown layer: Functional

### ISSUE THREAD

**Issue by rookie-yanyu** [Shawn-Shan/fawkes#131]
we met an error to run with `python protection.py -d /home/dl5/dataset/mylfw --mode high -g 0`.

> /home/dl5/conda/envs/tf2.0/bin/python /home/dl5/fawkes-master/fawkes/protection.py -d /home/dl5/dataset/mylfw --mode high -g 0
Using TensorFlow backend.
1 Physical GPUs, 1 Logical GPU
Traceback (most recent call last):
  File "/home/dl5/fawkes-master/fawkes/protection.py", line 201, in <module>
    main(*sys.argv)
  File "/home/dl5/fawkes-master/fawkes/protection.py", line 192, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size, mode=args.mode)
  File "/home/dl5/fawkes-master/fawkes/protection.py", line 56, in __init__
    self.feature_extractors_ls = [load_extractor(name) for name in extractors]
  File "/home/dl5/fawkes-master/fawkes/protection.py", line 56, in <listcomp>
    self.feature_extractors_ls = [load_extractor(name) for name in extractors]
  File "/home/dl5/fawkes-master/fawkes/utils.py", line 437, in load_extractor
    model = keras.models.load_model(model_file)
  File "/home/dl5/conda/envs/tf2.0/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/dl5/conda/envs/tf2.0/lib/python3.7/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/home/dl5/conda/envs/tf2.0/lib/python3.7/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/dl5/conda/envs/tf2.0/lib/python3.7/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/dl5/conda/envs/tf2.0/lib/python3.7/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/home/dl5/conda/envs/tf2.0/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Functional

the environment information is listed as follows:

>  (tf2.0) dl5@dl5:~/fawkes-master$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

>  python=3.7 
tensorflow-gpu = 2.0.0
numpy = 1.20.1
keras  = 2.3.1 
keras-applications =1.0.8 
keras-base =2.3.1  
keras-preprocessing=1.1.2  
mtcnn=0.1
pillow=8.2.0
bleach=3.3.0

it seems that i should add the parameter of `custom_objects` like `{"Functional": Functional}`,  but i don't know where to find the Functional class in the project

**Comment by MarkSCQ** [comment]
I have the same error messages when using current version. I would suggest using v0.3.2. The previous version 0.3.2, using tf1.15.0 is much stable than the current version. ヾ(•ω•`)o

**Comment by rookie-yanyu** [comment]
> I have the same error messages when using current version. I would suggest using v0.3.2. The previous version 0.3.2, using tf1.15.0 is much stable than the current version. ヾ(•ω•`)o

@MarkSCQ Thank you for your help. I did solve the problem by switching the tag to v0.3. amazing!

**Comment by rookie-yanyu** [comment]
There are some differences between current version and previous version 0.3.2.If I want to use the current version,How to deal with the problem **"keras.models.load_model Unknown layer: Functional"** ?

**Comment by Shawn-Shan** [comment]
Ah the issue is with tensorflow dependency. I fixed the issue in the latest commit. Please uninstall fawkes, then update the repo. Let me know if it does not fix the issue.
