### ISSUE TITLE
failed to execute script app

### ISSUE THREAD

**Issue by massouu** [Shawn-Shan/fawkes#142]
This error is still present in the latest version v1.0
Do you have a solution for that 
![Uploading Screenshot 2021-07-09 000238.png…]()
?

**Comment by Shawn-Shan** [comment]
I need more information. what is your OS?

**Comment by massouu** [comment]
Windows 10 - 64 bit
I also tested on Windows 11 And this error still existed

**Comment by Peter2090** [comment]
Same problem. Did anyone find a solution?
Windows 10, Using latest Fawkes downloaded yesterday.
If I run fawkes_binary_windows-v1.0.exe from a command-line I get this:
Traceback (most recent call last):
  File "fawkes\protection.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "tensorflow\__init__.py", line 41, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "tensorflow\python\__init__.py", line 41, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "tensorflow\python\eager\context.py", line 35, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "tensorflow\python\pywrap_tfe.py", line 29, in <module>
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
[17816] Failed to execute script protection

**Comment by cvincer** [comment]
12th April'22

I also have the same problem.....ant simple answer out there ......anywhere I can go to to get the pre (W10) v1.0 version?
![Screenshot_1](https://user-images.githubusercontent.com/103469746/162856844-ddac1df6-0a58-4a6f-81d1-e7fac8570820.png)

![Screenshot_2](https://user-images.githubusercontent.com/103469746/162856866-92240e37-2b2c-4d39-9bae-9be5cfe0de99.png)

Thank You

**Comment by Peter2090** [comment]
I think this is because your CPU does not support the required instruction set for the tensor flow library/installer in use. Check your CPU on the Intel or AMD website - best to go to the source rather than use a tool to check.

**Comment by AlekseevichIvan** [comment]
![Снимок экрана 2022-07-22 131546](https://user-images.githubusercontent.com/100844313/180418629-45669149-e2a6-4613-b879-67deaa802592.jpg)
![Снимок экрана 2022-07-22 131429](https://user-images.githubusercontent.com/100844313/180418673-fb16d4ad-d7ce-45c7-a632-7581b6da6e6c.jpg)
 Вот моя система, но программа не запускается, ошибка! Как это исправить?
