### ISSUE TITLE
Import error: from keras.utils import Progbar

### ISSUE THREAD

**Issue by leoleozhu** [Shawn-Shan/fawkes#148]
Command version fails with the following message.

`Traceback (most recent call last):
  File "/Users/leo/.Envs/global/bin/fawkes", line 5, in <module>
    from fawkes import main
  File "/Users/leo/.Envs/global/lib/python3.9/site-packages/fawkes/__init__.py", line 9, in <module>
    from .differentiator import FawkesMaskGeneration
  File "/Users/leo/.Envs/global/lib/python3.9/site-packages/fawkes/differentiator.py", line 11, in <module>
    from fawkes.utils import preprocess, reverse_preprocess
  File "/Users/leo/.Envs/global/lib/python3.9/site-packages/fawkes/utils.py", line 24, in <module>
    from keras.utils import Progbar
ImportError: cannot import name 'Progbar' from 'keras.utils' (/Users/leo/.Envs/global/lib/python3.9/site-packages/keras/utils/__init__.py)`

**Comment by Shawn-Shan** [comment]
It should be caused by wrong keras version. Can you reinstall keras to the version we specified in requirement.txt?

**Comment by leoleozhu** [comment]
> It should be caused by wrong keras version. Can you reinstall keras to the version we specified in requirement.txt?

Yes. Working now. Thanks.

**Comment by PorcelainMouse** [comment]
Hmm, there's no requirements.txt any more.
