### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by marli** [Shawn-Shan/fawkes#17]
Protection fails with the following error:

Traceback (most recent call last):
  File "fawkes/protection.py", line 199, in <module>
  File "fawkes/protection.py", line 195, in main
  File "fawkes/protection.py", line 137, in run_protection
  File "fawkes/utils.py", line 172, in merge_faces
IndexError: index 1 is out of bounds for axis 0 with size 1
[7235] Failed to execute script protection

Please let me know if there are other details I can share.

**Comment by Shawn-Shan** [comment]
see https://github.com/Shawn-Shan/fawkes/issues/6#issuecomment-660714588.
