### ISSUE TITLE
Cannot be run in Linux (ubuntu)

### ISSUE THREAD

**Issue by Nocturnethy** [Shawn-Shan/fawkes#187]
Hello Dev-Team,

could you please detail out your manual for running fawkes/protection on linux systems?

I can neither open it by "start application" nor execute it via shell:

![image](https://github.com/user-attachments/assets/7899eb4e-6d0f-4569-8a27-f94aa166dc84)
--> "command not found"

Thanks for help!

**Comment by Tup0lev** [comment]
instead of "protection", run "./protection -d ./imgs --mode high"

**Comment by andrewpking** [comment]
Worse now. Won't even install via Pip on Ubuntu 26, this is functionally abandonware:

Collecting fawkes
  Downloading fawkes-1.0.4-py3-none-any.whl.metadata (3.9 kB)
Collecting numpy>=1.19.5 (from fawkes)
  Downloading numpy-2.4.6-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
INFO: pip is looking at multiple versions of fawkes to determine which version is compatible with other requirements. This could take a while.
Collecting fawkes
  Downloading fawkes-1.0.3-py3-none-any.whl.metadata (3.9 kB)
  Downloading fawkes-1.0.2-py3-none-any.whl.metadata (3.8 kB)
  Downloading fawkes-0.0.8-py3-none-any.whl.metadata (4.1 kB)
Collecting numpy==1.16.4 (from fawkes)
  Downloading numpy-1.16.4.zip (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 33.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Running from numpy source directory.
      <string>:390: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      /tmp/pip-install-bpy_3xbs/numpy_b69fce3a1bf54ff0b125a3bb51864719/numpy/distutils/misc_util.py:476: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
        return is_string(s) and ('*' in s or '?' is s)
      Traceback (most recent call last):
        File "/home/drew/img/fawkes/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/home/drew/img/fawkes/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/drew/img/fawkes/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 175, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-ykrzewxs/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-ykrzewxs/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ykrzewxs/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 415, in <module>
        File "<string>", line 394, in setup_package
        File "/tmp/pip-install-bpy_3xbs/numpy_b69fce3a1bf54ff0b125a3bb51864719/numpy/distutils/__init__.py", line 6, in <module>
          from . import ccompiler
        File "/tmp/pip-install-bpy_3xbs/numpy_b69fce3a1bf54ff0b125a3bb51864719/numpy/distutils/ccompiler.py", line 111, in <module>
          replace_method(CCompiler, 'find_executables', CCompiler_find_executables)
                         ^^^^^^^^^
      NameError: name 'CCompiler' is not defined. Did you mean: 'ccompiler'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by andrewpking** [comment]
In response to my previous version hell, if you look in the pull requests, it looks like a very talented developer managed to use Poetry to lock in the dependencies and make it work. I made a comment in that pull request on how to run it on Linux.
