### ISSUE TITLE
Could not install fawkes with pip

### ISSUE THREAD

**Issue by kevinsmia1939** [Shawn-Shan/fawkes#2]
Hello,
I could not install fawkes on openSUSE Tumbleweed with pip.
tensorflow<=1.14.0,>=1.13.1 is not satisfied. It look like the latest version is now 1.15.x.
Does tensorflow have to be strictly between 1.14.0 and 1.13.1? 
Thanks

```
kev@linux:~> sudo pip install fawkes
[sudo] password for root: 
Requirement already satisfied: fawkes in /usr/lib/python3.8/site-packages (0.0.6)
Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting keras==2.2.5
  Downloading Keras-2.2.5-py2.py3-none-any.whl (336 kB)
     |████████████████████████████████| 336 kB 1.1 MB/s 
Collecting numpy==1.16.4
  Downloading numpy-1.16.4.zip (5.1 MB)
     |████████████████████████████████| 5.1 MB 5.2 MB/s 
Collecting opencv-python>=4.2.0.34
  Downloading opencv_python-4.3.0.36-cp38-cp38-manylinux2014_x86_64.whl (43.7 MB)
     |████████████████████████████████| 43.7 MB 4.5 MB/s 
Requirement already satisfied: pillow>=7.0.0 in /usr/lib64/python3.8/site-packages (from fawkes) (7.1.2)
Requirement already satisfied: scikit-image in /usr/lib64/python3.8/site-packages (from fawkes) (0.16.2)
Collecting sklearn
  Downloading sklearn-0.0.tar.gz (1.1 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow<=1.14.0,>=1.13.1 (from fawkes) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1)
ERROR: No matching distribution found for tensorflow<=1.14.0,>=1.13.1 (from fawkes)
```

**Comment by pluja** [comment]
You need tensorflow latest version. Try with this before installing Fawkes:

`python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl`

**Comment by Shawn-Shan** [comment]
We have only tested on those versions, but I believe any Tensorflow 1 version after 1.8 should work. Tensorflow 2.0 is not supported.

**Comment by kevinsmia1939** [comment]
Hi, I compiled from source and this error occur. It seems to insist that it want tensorflow<=1.14.0,>=1.13.1 and not higher.

Thanks

```
kev@linux:~> fawkes -d /home/kev-test/Desktop/fawkes\ test/ --mode high
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tensorflow 2.1.1 (/usr/lib64/python3.8/site-packages), Requirement.parse('tensorflow<=1.14.0,>=1.13.1'), {'fawkes'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fawkes", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tensorflow<=1.14.0,>=1.13.1' distribution was not found and is required by fawkes
```

**Comment by kevinsmia1939** [comment]
Hello,

I compiled from source, but it seems that fawkes does not want tensorflow 1.15.3, it only want tensorflow<=1.14.0,>=1.13.1.

```
kev@linux:~> pip list | grep tensorflow
tensorflow                    1.15.3     
kev@linux:~> fawkes -d /home/kev-test/Desktop/fawkes\ test/ --mode high
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tensorflow 1.15.3 (/usr/lib64/python3.8/site-packages), Requirement.parse('tensorflow<=1.14.0,>=1.13.1'), {'fawkes'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fawkes", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tensorflow<=1.14.0,>=1.13.1' distribution was not found and is required by fawkes
```

**Comment by Shawn-Shan** [comment]
Oh yes, I will make a patch today that should fix this.

**Comment by kevinsmia1939** [comment]
Hello,

Wouldn't it be better to just include tensorflow >= 1.12.0 and have no limit to maximum version, that would make fawkes failed every time tensorflow update? Thanks.

**Comment by Shawn-Shan** [comment]
No, fawkes does not works on >2.0 and, if you want to try tf versions that are not tested, you should clone the repo, install your fav tf version, and run the protection.py with python3 directly.

**Comment by kevinsmia1939** [comment]
Alright thanks
