### ISSUE TITLE
mtcnn.p.gz failure on Windows

### ISSUE THREAD

**Issue by LDL707** [Shawn-Shan/fawkes#4]
When I try running Fawkes, I get the following output: 

`Traceback (most recent call last):
  File "urllib\request.py", line 1318, in do_open
  File "http\client.py", line 1239, in request
  File "http\client.py", line 1285, in _send_request
  File "http\client.py", line 1234, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 964, in send
  File "http\client.py", line 936, in connect
  File "socket.py", line 724, in create_connection
  File "socket.py", line 713, in create_connection
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fawkes\utils.py", line 520, in get_file
  File "urllib\request.py", line 248, in urlretrieve
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 526, in open
  File "urllib\request.py", line 544, in _open
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 1346, in http_open
  File "urllib\request.py", line 1320, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fawkes\protection.py", line 171, in <module>
  File "fawkes\protection.py", line 131, in main
  File "fawkes\utils.py", line 95, in __init__
  File "fawkes\utils.py", line 524, in get_file
Exception: URL fetch failure on http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz: None -- [WinError 10061] No connection could be made because the target machine actively refused it
[25400] Failed to execute script protection`

**Comment by Shawn-Shan** [comment]
Seems to be a connection error. Can you try to see whether you can download the mtcnn.p.gz file by directly entering the url ( http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz) to your browser? If you can, please try again to see if it successfully downloads the file.

**Comment by LDL707** [comment]
It downloads both inside the browser, and using the command line (using wget for Windows). 

I still get the error using Fawkes, though.

**Comment by Riajyuu** [comment]
@Shawn-Shan you should realize Windows CMD is too hard to set proxy properly. So if you are relying on anything, you should package them all or simply provide a network setting interface.

**Comment by DenisSouth** [comment]
You can try to run it on Google Colab
I made an instruction https://github.com/DenisSouth/fawkes_use

**Comment by Shawn-Shan** [comment]
We just released windows .exe software for Fawkes. It should address these issues.
