### ISSUE TITLE
Corrupted Windows binary

### ISSUE THREAD

**Issue by emjoywill** [Shawn-Shan/fawkes#44]
您好，请问下这个怎么解决呢？
PS F:\job1\fawkes_binary_windows-v0.2 (1)> .\protection-v0.2.exe -d F:/job1/fawkes_img
Traceback (most recent call last):
  File "fawkes\protection.py", line 210, in <module>
  File "fawkes\protection.py", line 203, in main
  File "fawkes\protection.py", line 61, in __init__
  File "fawkes\protection.py", line 61, in <listcomp>
  File "fawkes\utils.py", line 367, in load_extractor
  File "keras\engine\saving.py", line 492, in load_wrapper
  File "keras\engine\saving.py", line 583, in load_model
  File "keras\utils\io_utils.py", line 191, in __init__
  File "h5py\_hl\files.py", line 408, in __init__
  File "h5py\_hl\files.py", line 173, in make_fid
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 9510912, sblock->base_addr = 0, stored_eof = 29292232)
[1828] Failed to execute script protection
PS F:\job1\fawkes_binary_windows-v0.2 (1)>

_Originally posted by @zidielucky in https://github.com/Shawn-Shan/fawkes/issues/24#issuecomment-665500841_

**Comment by emjoywill** [comment]
This is a separate issue from #24.

It looks like the binary download was corrupted. Can you download and try again?

**Comment by zidielucky** [comment]
您好，非常感谢您的回答，请问下运行下载的最新版的Fawkes.exe(v0.3)，选择图片直接运行之后，在图片原目录文件中没有生成隐藏图片是什么原因呀？Fawkes.exe运行之后直接闪退了，
![image](https://user-images.githubusercontent.com/54791204/88997510-7d22c180-d322-11ea-9a05-7f05b56b0a2d.png)
![Uploading image.png…]()

**Comment by Shawn-Shan** [comment]
Can you download windows binary and try to run on images? It will be much easier to debug

**Comment by zidielucky** [comment]
> 您可以下载Windows二进制文件并尝试在图像上运行吗？调试起来会容易得多

您好，在二进制文件中也尝试了，是这个状态，请问下第二步怎么操作的呢？好像是没设置正确
![image](https://user-images.githubusercontent.com/54791204/89138350-e64a4500-d56d-11ea-96f7-fdc0e7e88368.png)

**Comment by Shawn-Shan** [comment]
The download is stuck due to your network connection. Depends on your location, the download might be really slow. Please consider using a different network if possible.

**Comment by zidielucky** [comment]
> The download is stuck due to your network connection. Depends on your location, the download might be really slow. Please consider using a different network if possible.

是网络慢的原因导致隐藏图片无法生成吗？第二步把文件目录设为保护具体怎么操作的呢？会不会也有这个原因

**Comment by Shawn-Shan** [comment]
Yes, Fawkes software will download some models at first, and without them the code won't run.
