### ISSUE TITLE
Failed to execute script protection

### ISSUE THREAD

**Issue by krnmgn69** [Shawn-Shan/fawkes#48]
Hello! Can you help me to solve this error please.

OS: Windows 7 Professional 64-bit (6.1, Build 7601)
Memory: 8192MB RAM (8 GB usable)
Processor: Intel(R) Pentium(R) CPU G3460 @3.50Ghz
Display adapter: Intel(R) HD Graphics (integrated)

C:\>cd fawkes

C:\fawkes>dir
 Volume in drive C has no label.
 Volume Serial Number is F85C-E6F1

 Directory of C:\fawkes

04.08.2020  16:57    <DIR>          .
04.08.2020  16:57    <DIR>          ..
29.07.2020  19:06           191,206 foto.jpg
03.08.2020  05:48       130,956,617 protection-v0.3.exe
               2 File(s)    131,147,823 bytes
               2 Dir(s)  87,851,528,192 bytes free

C:\fawkes>protection-v0.3.exe -d c:\fawkes
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protection.py", line 13, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\__init__.py", line 28, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace above this error message when asking for help.
[5928] Failed to execute script protection

C:\fawkes>

Thank you!

**Comment by emjoywill** [comment]
This looks like a tensorflow error, not a Fawkes error. Did you try following the link that came up with the error (i.e. https://www.tensorflow.org/install/errors) to see what might be wrong?
