### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by dragonxtek** [Shawn-Shan/fawkes#52]
After install it with python3 setup.py install without issues I run fawkes and I get the following issue:

> fawkes
Traceback (most recent call last):
  File "/usr/local/bin/fawkes", line 33, in <module>
    sys.exit(load_entry_point('fawkes==0.3.1', 'console_scripts', 'fawkes')())
  File "/usr/local/bin/fawkes", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/fawkes-0.3.1-py3.6.egg/fawkes/__init__.py", line 9, in <module>
    from .detect_faces import create_mtcnn, run_detect_face
  File "/usr/local/lib/python3.6/dist-packages/fawkes-0.3.1-py3.6.egg/fawkes/detect_faces.py", line 33, in <module>
    import tensorflow as tf
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/dragonxtek/.local/lib/python3.6/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 23, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

What I need to resolve?

**Comment by emjoywill** [comment]
This looks like a tensorflow error, not a Fawkes error. What version of tensorflow are you using?

**Comment by Mtemi** [comment]
keyword argument in python 3 appear when we try access a key value that is non existent. Look at the variable that is causing the error. and try access it without the key. It should give you a result that can guide you. From the result then extract they keys and consequently the values.

**Comment by dragonxtek** [comment]
> tensorflow

I have tensorflow (1.14.0)
