### ISSUE TITLE
Failed to execute script protection

### ISSUE THREAD

**Issue by CrasherX** [Shawn-Shan/fawkes#57]
I am on Windows 10 with Python 3.6 and Tensorflow 1.14.0 
Running the following command produces an error
`.\protection-v0.3.exe -d img`

```
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protection.py", line 13, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\__init__.py", line 28, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[5424] Failed to execute script protection
```

**Comment by CrasherX** [comment]
Same with Python 3.7

```
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protection.py", line 13, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\__init__.py", line 28, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[13028] Failed to execute script protection
```

**Comment by emjoywill** [comment]
This looks like an issue with your installation of Tensorflow. Have you tried navigating to the link listed in the error output to see what they suggest?

**Comment by CrasherX** [comment]
I found that my CPU doesn't support AVX instruction extensions. I'm guessing that's the problem.
