### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by brendan8c** [Shawn-Shan/fawkes#61]
Running the Fawkes-0.3.exe file gives an error.
Write a program. Do also for Windows 7
![2020-08-13 10_58_23-(f) Other](https://user-images.githubusercontent.com/61526280/90109125-07701a00-dd54-11ea-8e7e-ff9e4c84a5cd.jpg)
![2020-08-13 11_00_41-Система](https://user-images.githubusercontent.com/61526280/90109314-4f8f3c80-dd54-11ea-9b84-05609d83cedc.jpg)

**Comment by brendan8c** [comment]
**If I use the console**

D:\images>protection-v0.3.exe -d D:\images
Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_impor
t_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_impor
t_helper
ImportError: DLL load failed with error code -1073741795

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protection.py", line 13, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\__init__.py", line 28, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\__init__.py", line 49, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
ImportError: Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_impor
t_helper
  File "imp.py", line 297, in find_module
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
  File "c:\users\jonwe\appdata\local\programs\python\python37\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
  File "tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_impor
t_helper
ImportError: DLL load failed with error code -1073741795


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
[4312] Failed to execute script protection

D:\images>pause
Для продолжения нажмите любую клавишу . . .

**Comment by emjoywill** [comment]
The program is not designed to work for Windows 7 -- only for Windows 10+. Do you have an option to use that os instead?

**Comment by brendan8c** [comment]
No. I Am love Windows 7
I don't want to update it

**Comment by tredondo** [comment]
If you care about privacy, use Linux, even in a VM.

**Comment by brendan8c** [comment]
Linux does not have the same programs as Windows

**Comment by tredondo** [comment]
@brendan8c: Like what? You can run most Windows applications on Linux using [Wine](https://www.winehq.org/), which comes [included with certain Linux distributions](https://embeddedinventor.com/best-linux-distros-with-wine-preinstalled-an-analysis/). Anyway, this is getting off-topic.
