### ISSUE TITLE
Fawkes and Protection made the same mistake with Win10

### ISSUE THREAD

**Issue by yuanerjinyi** [Shawn-Shan/fawkes#71]
E:\images>fawkes -d imag
Traceback (most recent call last):
  File "e:\python3.7\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python3.7\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\python3.7\Scripts\fawkes.exe\__main__.py", line 7, in <module>
  File "e:\python3.7\lib\site-packages\fawkes\protection.py", line 210, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
  File "e:\python3.7\lib\site-packages\fawkes\protection.py", line 52, in __init__
    self.aligner = aligner(sess)
  File "e:\python3.7\lib\site-packages\fawkes\align_face.py", line 44, in aligner
    pnet, rnet, onet = create_mtcnn(sess, None)
  File "e:\python3.7\lib\site-packages\fawkes\detect_faces.py", line 285, in create_mtcnn
    dnet_weights = pickle.load(fp)
  File "e:\python3.7\lib\gzip.py", line 276, in read
    return self._buffer.read(size)
  File "e:\python3.7\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "e:\python3.7\lib\gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

E:\images>protection-v0.3.exe -d imag
Traceback (most recent call last):
  File "protection.py", line 225, in <module>
  File "protection.py", line 210, in main
  File "protection.py", line 52, in __init__
  File "align_face.py", line 44, in aligner
  File "detect_faces.py", line 285, in create_mtcnn
  File "gzip.py", line 276, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 482, in read
EOFError: Compressed file ended before the end-of-stream marker was reached
[14312] Failed to execute script protection

After reinstalling it many times, it doesn’t work, and the win10 fawkes.exe program ends when the picture is selected and it runs. It feels that it has no output at all. Does this model need to be connected to the Internet when it runs?

**Comment by emjoywill** [comment]
Yes, you need to be connected to the internet in order to run Fawkes the first time. It needs to download some models that are used in computation. Additionally, it looks like your initial download may have been corrupted. Please try deleting the ~/.fawkes directory and downloading/installing again.

**Comment by yuanerjinyi** [comment]
@emjoywill  Thank you very much, it has been resolved

**Comment by yuanerjinyi** [comment]
> 是的， 你需要连接到互联网， 才能第一次运行 Fawkes 。它需要下载一些用于计算的模型。此外，看起来您的初始下载可能已损坏。请尝试删除 +/.fawkes 目录并再次下载/安装。



> Yes, you need to be connected to the internet in order to run Fawkes the first time. It needs to download some models that are used in computation. Additionally, it looks like your initial download may have been corrupted. Please try deleting the ~/.fawkes directory and downloading/installing again.

Thank you very much, it has been resolved
