### ISSUE TITLE
[2768] Failed to execute script protection

### ISSUE THREAD

**Issue by dimscor** [Shawn-Shan/fawkes#76]
I do everything as in your guide, but see this error: [2768] Failed to execute script protection.
C:\Users\Administrator\Desktop>protection.exe -d D:\Images
Traceback (most recent call last):
  File "protection.py", line 225, in <module>
  File "protection.py", line 210, in main
  File "protection.py", line 53, in __init__
  File "protection.py", line 53, in <listcomp>
  File "utils.py", line 406, in load_extractor
  File "keras\engine\saving.py", line 492, in load_wrapper
  File "keras\engine\saving.py", line 583, in load_model
  File "keras\utils\io_utils.py", line 191, in __init__
  File "h5py\_hl\files.py", line 408, in __init__
  File "h5py\_hl\files.py", line 173, in make_fid
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 9986048, sblock->base_addr = 0, stored_eof = 29292232)
[2768] Failed to execute script protection

**Comment by emjoywill** [comment]
It seems like there was a corrupted download. This could be an issue with your local network connection.
